[package]
name = "ragi_shark_server_rust"
version = "0.1.0"
authors = ["ragingo <save.the.world.crush@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "*"
sha-1 = "^0.9.2"
base64 = "^0.13.0"
